fightclub/urls.py
from core.views import FighterViewSet
from rest_framework.routers import DefaultRouter
from django.conf.urls import patterns, include
from django.contrib import admin

urlpatterns = patterns('', (r'^admin/', include(admin.site.urls)),)

router = DefaultRouter()
router.register(r'fighters', FighterViewSet)
urlpatterns += router.urls

whowin/urls.py
from django.conf.urls import patterns, url
from whowin.views import FightView, FighterListView, TopTenView, FighterDetailView, AboutView, BottomTenView, StatsView, UserStatsView, ContactView, SuccessView

urlpatterns = patterns('',
                       url(r'^fight/(?P<f1>\w+)/(?P<f2>\w+)/$',
                           FightView.as_view(), name='fight'),
                       url(r'^fighters/$', FighterListView.as_view(), name='list'),
                       url(r'^topten/$', TopTenView.as_view(), name='topten'),
                       url(r'^bottomten/$',
                           BottomTenView.as_view(), name='bottomten'),
                       url(r'^fighters/(?P<slug>[\w-]+)/',
                           FighterDetailView.as_view(), name='detail'),
                       url(r'^stats/$', StatsView.as_view(), name='stats'),
                       url(r'^about/$', AboutView.as_view(), name='about'),
                       url(r'^userstats/$', UserStatsView.as_view(), name='userstats'),
                       url(r'^contact/$', ContactView.as_view(), name='contact'),
                       url(r'^success/$', SuccessView.as_view(), name='success'),

                       )

whowin/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Fighter(models.Model):
    name = models.CharField(max_length=50)
    SIDE_CHOICES = (
        ('E', 'Evil'),
        ('G', 'Good'),
        ('N', 'Neutral'),
    )
    side = models.CharField(max_length=1, choices=SIDE_CHOICES, default='N')
    description = models.TextField(default='')
    slug = models.SlugField(default=0, max_length=50, unique=True)
    rating = models.DecimalField(default=1600, max_digits=8, decimal_places=2)
    fightswon = models.IntegerField(default=0)
    fightslost = models.IntegerField(default=0)
    rank = models.IntegerField(default=0)

    def __unicode__(self):
        return '%s' % (self.name)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Fighter, self).save(*args, **kwargs)


class Fight(models.Model):
    member1 = models.ForeignKey(Fighter, related_name='fighter_1')
    member2 = models.ForeignKey(Fighter, related_name='fighter_2')
    user = models.ForeignKey(User, null=True, blank=True)

    member1_start_rank = models.IntegerField(null=True, blank=True)
    member1_end_rank = models.IntegerField(null=True, blank=True)
    member1_start_rating = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=2)
    member1_end_rating = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=2)
    member2_start_rank = models.IntegerField(null=True, blank=True)
    member2_end_rank = models.IntegerField(null=True, blank=True)
    member2_start_rating = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=2)
    member2_end_rating = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=2)

    winner = models.ForeignKey(Fighter, related_name='winner', null=True, blank=True)
    loser = models.ForeignKey(Fighter, related_name='loser', null=True, blank=True)
    start = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    end = models.DateTimeField(null=True, blank=True, auto_now=True)

    def __unicode__(self):
        return '%s v %s' % (self.member1, self.member2)

    def rankupdate(self, win):
        if win == self.member1:
            lose = self.member2
            win = self.member1
        else:
            lose = self.member1
            win = self.member2

        winnerval = 1 / (1 + 10 ** ((lose.rating - win.rating) / 400))
        loserval = 1 - winnerval

        win.rating += 20 * (1 - winnerval)
        win.fightswon += 1
        lose.rating += 20 * (0 - loserval)
        lose.fightslost += 1
        lose.save()
        win.save()

whowin/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail


class FighterSelectForm(forms.Form):

    def __init__(self, *args, **kwargs):
        choices = kwargs.pop("choices", [])
        super(FighterSelectForm, self).__init__(*args, **kwargs)
        self.fields["who_would_win_in_a_fight_between"] = forms.ChoiceField(
            widget=forms.RadioSelect,
            choices=choices)


class ContactForm(forms.Form):
    Fighter_Name = forms.CharField(max_length=100)
    Description = forms.CharField(widget=forms.Textarea)
    Email = forms.EmailField()

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)

    def send_email(self):
        cleaned_data = super(ContactForm, self).clean()
        subject = cleaned_data.get("Fighter_Name")
        message = cleaned_data.get("Description")
        user_email = cleaned_data.get("Email")
        from_email = settings.EMAIL_HOST_USER
        to_list = [user_email, settings.EMAIL_HOST_USER]

        send_mail(subject, message, from_email, to_list, fail_silently=True)
        pass

whowin/views.py
from random import sample
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import FormView
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from whowin.forms import FighterSelectForm, ContactForm
from whowin.models import Fight, Fighter
import matplotlib.pyplot as plt, mpld3
import numpy as np
from mpld3 import plugins


class FightView(FormView):

    fight = None
    template_name = 'whowin/match.html'

    def get_success_url(self):
        return reverse('home')

    def get_context_data(self, **kwargs):
        context = super(FightView, self).get_context_data(**kwargs)
        context['m1'] = Fighter.objects.get(id=self.kwargs['f1'])
        context['m2'] = Fighter.objects.get(id=self.kwargs['f2'])
        return context

    def get_form(self, form_class):

        if self.kwargs['f1'] == self.kwargs['f2']:
            self.template_name = '404.html'

        a = Fighter.objects.get(id=self.kwargs['f1'])
        b = Fighter.objects.get(id=self.kwargs['f2'])
        if self.request.user.is_authenticated():
            self.fight = Fight(member1=a, member2=b, member1_start_rank=a.rank,
                               member2_start_rank=b.rank, member1_start_rating=a.rating,
                               member2_start_rating=b.rating, user=self.request.user)
        else:
            self.fight = Fight(member1=a, member2=b, member1_start_rank=a.rank,
                               member2_start_rank=b.rank, member1_start_rating=a.rating,
                               member2_start_rating=b.rating, user=None)

        choices = [(self.fight.member1.id, self.fight.member1.name),
                   (self.fight.member2.id, self.fight.member2.name)]
        kwargs = super(FightView, self).get_form_kwargs()
        kwargs.update({"choices": choices})
        form = FighterSelectForm(**kwargs)
        return form

    def form_valid(self, form):
        win = Fighter.objects.get(
            id=form.cleaned_data['who_would_win_in_a_fight_between'])

        if win == self.fight.member1:
            lose = self.fight.member2
        else:
            lose = self.fight.member1
        self.fight.rankupdate(win)
        self.fight.member1_end_rating = self.fight.member1.rating
        self.fight.member2_end_rating = self.fight.member2.rating
        self.fight.winner = win
        self.fight.loser = lose
        self.fight.save()

        fighterlist = list(Fighter.objects.order_by('-rating', 'name'))
        for fighter in fighterlist:
            r = fighterlist.index(fighter)
            r += 1
            fighter.rank = r
            fighter.save()

        fighter1 = Fighter.objects.get(id=self.fight.member1.id)
        fighter2 = Fighter.objects.get(id=self.fight.member2.id)
        self.fight.member1_end_rank = fighter1.rank
        self.fight.member2_end_rank = fighter2.rank
        self.fight.save()

        return super(FightView, self).form_valid(form)


class TopTenView(ListView):
    queryset = Fighter.objects.order_by('-rating')[:10]
    context_object_name = 'fighter_list'
    template_name = 'whowin/topten.html'


class BottomTenView(ListView):
    queryset = Fighter.objects.order_by('rating')[:10]
    context_object_name = 'fighter_list'
    template_name = 'whowin/bottomten.html'


class FighterDetailView(DetailView):
    model = Fighter
    template_name = 'whowin/fighterdetail.html'

    def get_context_data(self, **kwargs):
        context = super(FighterDetailView, self).get_context_data(**kwargs)
        ratings = []
        dates = []
        for fight in Fight.objects.all():
            if fight.member1 == self.object:
                ratings.append(fight.member1_end_rating)
                dates.append(fight.end)
            elif fight.member2 == self.object:
                ratings.append(fight.member2_end_rating)
                dates.append(fight.end)
            else:
                pass

        fightswon = Fight.objects.filter(winner=self.object).count()
        fightslost = Fight.objects.filter(loser=self.object).count()
        context['won'] = fightswon
        context['lost'] = fightslost

        fig, ax = plt.subplots()
        ax.plot(dates, ratings)
        rating_fig = mpld3.fig_to_html(fig)
        context = {'ratingfig': rating_fig}
        return context


class FighterListView(ListView):
    template_name = 'whowin/fighterlist.html'
    context_object_name = 'all_fighters'
    queryset = Fighter.objects.order_by('name')


class AboutView(TemplateView):
    template_name = 'whowin/about.html'

    def get_context_data(self, **kwargs):
        fig, ax = plt.subplots()
        x = np.linspace(-2, 2, 20)
        y = x[:, None]
        X = np.zeros((20, 20, 4))
        X[:, :, 0] = np.exp(- (x - 1) ** 2 - (y) ** 2)
        X[:, :, 1] = np.exp(- (x + 0.71) ** 2 - (y - 0.71) ** 2)
        X[:, :, 2] = np.exp(- (x + 0.71) ** 2 - (y + 0.71) ** 2)
        X[:, :, 3] = np.exp(-0.25 * (x ** 2 + y ** 2))
        im = ax.imshow(X, extent=(10, 20, 10, 20),
                       origin='lower', zorder=1, interpolation='nearest')
        fig.colorbar(im, ax=ax)
        ax.set_title('An Image', size=20)
        plugins.connect(fig, plugins.MousePosition(fontsize=14))

        html_fig = mpld3.fig_to_html(fig)

        context = {'theFig': html_fig}
        return context


class StatsView(TemplateView):

    template_name = 'whowin/stats.html'

    def get_context_data(self, **kwargs):
        context = super(StatsView, self).get_context_data(**kwargs)
        total = Fight.objects.count()
        num = Fighter.objects.count()
        context['total'] = total
        context['numfighters'] = num
        return context


class ContactView(FormView):
    template_name = 'whowin/contact.html'
    form_class = ContactForm

    def get_success_url(self):
        return reverse('success')

    def form_valid(self, form):
        form.send_email()
        return super(ContactView, self).form_valid(form)


class SuccessView(TemplateView):
    template_name = 'whowin/success.html'


def home_view(request):
    fi1, fi2 = sample(Fighter.objects.all(), 2)

    return HttpResponseRedirect(reverse('fight', kwargs={'f1': fi1.id,
                                                         'f2': fi2.id
                                                         }))


class UserStatsView(TemplateView):
    template_name = 'whowin/userstats.html'

    def dispatch(self, request, *args, **kwargs):

        if not self.request.user.is_authenticated():
            return redirect('/account/login/')
        else:
            return super(UserStatsView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserStatsView, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        context['total'] = Fight.objects.filter(user=self.request.user).count()
        context['previous5'] = Fight.objects.filter(user=self.request.user).order_by('start').reverse()[:5]
        return context

templates/whowin/about.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "About" %}{% endblock %}

{% block body_class %}{% endblock %}

{% block banner %}
	{% block content %}
	<script type="text/javascript"
	src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
	</script>

	    <h1 style="text-align:left;">About
		    <span style="float:right;">
			    <a href="https://twitter.com/_thefightclub" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @_thefightclub</a>

			    <iframe src="http://ghbtns.com/github-btn.html?user=Fight-Club&repo=fightclub&type=watch&count=true&size=large"
				allowtransparency="true" frameborder="0" scrolling="0" width="170" height="30">
				</iframe>
		    </span>
	    </h1>

	    <h3>The Maths</h3>
	        <p class="lead">
	        You may be wondering how your votes affect the overall rankings on the site, allow us to explain...
	        <br><br>
	        Every Fighter has a hidden rating that the general public never see. Every time you choose the winner of a Fight, the server uses the <a href="http://en.wikipedia.org/wiki/Elo_rating_system" target="_blank" >ELO Algorithm</a> to update each Fighters rankings. The Fighters are listed in order of rating, and voila! We have our new Top10.
	        <br><br>
	        I'm intrigued, tell me more...
	        <br><br>
	        How about we do an example? You're given a fight between Gandalf and Han Solo, Gandalf has a hidden rating of 1720 and Han's is 1550. First, the algorithm calulates the probability of each Fighter winning based on these ratings.
	        <br><br>
			Probability Gandalf Wins = \( \frac{1}{1 + 10^{\frac{\text{Hans Rating - Gandalfs Rating}}{400}}} = 0.727 \)
			<br><br>
			Probability Han Wins = \( \frac{1}{1 + 10^{\frac{\text{Gandalfs Rating - Hans Rating}}{400}}} = 0.273 \)
			<br><br>
			Now, lets pretend that you say Gandalf will win (obviously he would). He gains \( 20(1 - 0.727) = 5.46 \) points onto his rating and Han loses the same amount.<br>
			In the unlikely even that Han won (is that even possible?..). He gains \( 20(1 - 0.273) = 14.54 \) points onto his rating and Gandalf loses that amount.
			<br><br>
			Notice that if the Fighter with the lower rating wins, he gains more points than if the Fighter with the higher rating wins. This process happens after every fight that takes place and it is what ensures TheFightClub displays a fair representation of the public's opinion.
	        </p>

	        {{ theFig|safe }}

	    <h3>The Team</h3>
	        <p class="lead">This website was created by James Campbell, Sam Ewen, Samuel Dunkley and Matt Jones as part of a project for their degree. They all currently study Mathematics at Cardiff University and have top banter because they are top lads.</p>
	    <ul>
	        <div class="g-person" data-width="200" data-href="//plus.google.com/103944008095354003273" data-showtagline="false" data-showcoverphoto="false" data-rel="author"></div>
		    <div class="g-person" data-width="200" data-href="//plus.google.com/107921561116596398340" data-showtagline="false" data-showcoverphoto="false" data-rel="author"></div>
		    <div class="g-person" data-width="200" data-href="//plus.google.com/109674045473531460047" data-showtagline="false" data-showcoverphoto="false" data-rel="author"></div>
		    <div class="g-person" data-width="200" data-href="https://plus.google.com/100765228447202127252" data-showtagline="false" data-showcoverphoto="false" data-rel="author"></div>
	    </ul>


	    <!-- Place this tag after the last widget tag. -->
		<script type="text/javascript">
		  window.___gcfg = {lang: 'en-GB'};

		  (function() {
		    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
		    po.src = 'https://apis.google.com/js/platform.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  })();
		</script>

		<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
	{% endblock %}
{% endblock %}

templates/whowin/bottomten.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Bottom 10" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
	{% block content %}
	    <h2>Bottom 10</h2>
	    <ul class="list-unstyled">
	        {% for fighter in object_list reversed %}
	            <li>{{ fighter.rank }} - <a href="{% url 'detail' fighter.slug %}">{{ fighter.name }}</a></li>
	        {% endfor %}
	    </ul>
	{% endblock %}
{% endblock %}

templates/whowin/contact.html
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.2.0/pure-min.css">
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "User Stats" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    {% block content %}
        <h1>Contact Us</h1>

        <br>
        <h3>Get in Touch</h3>
            <p class="lead">
            We really want to know what you think of our site, so please don't hesitate to get in touch! Good or back we need your feed back. Send us a message at <a href="https://twitter.com/intent/tweet?screen_name=_thefightclub&text=%23GandalfVsDumbledore" class="twitter-mention-button" data-size="large" data-related="_thefightclub">Tweet to @_thefightclub</a> and tell us your deepest darkest secrets.
            </p>
        <br>
        <h3>Make a suggestion</h3>
            <p class="lead">
            If you think we've missed out someone important from our list of Fighters, just send us a quick suggestion here. Make sure to include a decent description so we know who you're on about!
            </p>
            <form class="pure-form pure-form-stacked" action="" method="post">{% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="pure-button pure-button-primary" value="Send" />
            </form>
        <br>
        <h3>Found a bug?</h3>
            <p class="lead">
            If you've found something that doesn't seem to work correctly, or you have an amazing idea on how to improve the site, please head over to <a href="https://github.com/Fight-Club/fightclub/issues">GitHub</a> and create a new issue. We'll try and respond as soon as we can. Thanks you!
            </p>
        <br>
        <h3>Get Involved</h3>
            <p class="lead">
            Finally, for those of you feel like writing a bit of code. Please feel free to fork our repository at <a href="https://github.com/Fight-Club/fightclub/">GitHub</a> and submit a pull request. We want as many people to get involved as possible.
            </p>

    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    {% endblock %}
{% endblock %}

templates/whowin/fighterdetail.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Info" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
	{% block content %}
	    <h2>{{fighter.name}}</h2>
	    <ul class="list-unstyled">
		    	<li>Current Ranking: {{ fighter.rank }}</li>
	            <li>Fights Won: {{ won }}</li>
	            <li>Fights Lost: {{ lost }}</li>
	            <li>Side: {{ fighter.get_side_display }}</li>
	            <li>Description: {{ fighter.description|safe }}</li>
	    </ul>

		{{ ratingfig|safe }}

	{% endblock %}

{% endblock %}

templates/whowin/fighterlist.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Fighters" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
	{% block content %}
	    <h2>Fighters</h2>
	    <ul class="list-inline">
	        {% for fighter in object_list %}
	            <li><a href="{% url 'detail' fighter.slug %}">{{ fighter.name }}</a></li>
	        {% endfor %}
	    </ul>
	{% endblock %}
{% endblock %}

templates/whowin/match.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Fight" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    {% block content %}
	    <h2>Fight! <a href="https://twitter.com/intent/tweet?button_hashtag=GandalfVsDumbledore&text=I%20love%20the%20FightClub" class="twitter-hashtag-button" data-lang="en" data-related="jasoncosta">Tweet #GanalfVsDumbledore</a>
        </h2>


	    <form class="form-inline" role="form" action="" method="post">
            {% csrf_token %}
		    {{ form.as_p }}
		    <button type="submit" class="btn btn-action">Submit</button>
            <button class="btn btn-info" data-toggle="modal" data-target=".bs-example-modal-lg">Who are they?</button>
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Descriptions</h4>
                    </div>
                    <div class="modal-body">
                        <h3>{{ m1.name }}</h3>
                        <p class="lead">
                        {{ m1.description|safe }}
                        </p>
                        <h3>{{ m2.name }}</h3>
                        <p class="lead">
                        {{ m2.description|safe }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <a class="btn btn-warning" href="{% url 'home' %}">Skip</a>
		</form>

        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	{% endblock %}
{% endblock %}

templates/whowin/results.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Rankings" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
	{% block content %}
	    <h2>Top 10</h2>
	    <ul>
	        {% for fighter in object_list %}
	            <li>{{ fighter.rank }} - <a href="{% url 'detail' fighter.slug %}">{{ fighter.name }}</a></li>
	        {% endfor %}
	    </ul>
	{% endblock %}
{% endblock %}

templates/whowin/stats.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Stats" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
	{% block content %}
	    <h2>Stats</h2>
	    <ul class="list-unstyled">
	        <li>{% trans "Total Fights Fought: " %}{{total}}</li>
	        <li>{% trans "Number of Fighters: " %}{{numfighters}}</li>
	    </ul>
	{% endblock %}
{% endblock %}

templates/whowin/success.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "About" %}{% endblock %}

{% block body_class %}{% endblock %}

{% block banner %}
    {% block content %}
        <h1>Message Sent!</h1>
    {% endblock %}
{% endblock %}

templates/whowin/topten.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Top 10" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
	{% block content %}
	    <h2>Top 10</h2>
	    <ul class="list-unstyled">
	        {% for fighter in object_list %}
	            <li>{{ fighter.rank }} - <a href="{% url 'detail' fighter.slug %}">{{ fighter.name }}</a></li>
	        {% endfor %}
	    </ul>
	{% endblock %}
{% endblock %}

templates/whowin/userstats.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "User Stats" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}
    {% block content %}
        <h2>{{user}}'s Stats</h2>
        <ul>
            {% trans "Total Fights Fought: " %}{{total}}

            <h3>Previous Fights</h3>
            <div class="table-responsive">
            <table class="table">
            <tr>
              <th>Date</th>
              <th>Winner</th>
              <th>Loser</th>
            </tr>

            {% for fight in previous5 %}
                <tr>
                  <td>{{ fight.start }}</td>
                  <td>{{ fight.winner }}</td>
                  <td>{{ fight.loser }}</td>
                </tr>
            {% endfor %}
            </table>
            </div>

        </ul>
    {% endblock %}
{% endblock %}